version: "3"

services:
  mk-blog-nextjs:
    container_name: mk-blog-nextjs
    image: ngockhoi96/mkblognextjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./.next/standalone/.:/app
      - /app/.next
      - /app/node_modules
    ports:
      - "4000:4000"
